{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "cveMetadata": {
        "cveId": "CVE-2024-0654",
        "assignerOrgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
        "state": "PUBLISHED",
        "assignerShortName": "VulDB",
        "dateReserved": "2024-01-17T14:26:16.294Z",
        "datePublished": "2024-01-18T01:00:07.149Z",
        "dateUpdated": "2024-02-09T19:12:11.048Z"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
                "shortName": "VulDB",
                "dateUpdated": "2024-02-09T19:12:11.048Z"
            },
            "title": "DeepFaceLab Util.py deserialization",
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "CWE",
                            "cweId": "CWE-502",
                            "lang": "en",
                            "description": "CWE-502 Deserialization"
                        }
                    ]
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "DeepFaceLab",
                    "versions": [
                        {
                            "version": "pretrained DF.wf.288res.384.92.72.22",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A vulnerability, which was classified as problematic, was found in DeepFaceLab pretrained DF.wf.288res.384.92.72.22. Affected is an unknown function of the file mainscripts/Util.py. The manipulation leads to deserialization. Local access is required to approach this attack. The exploit has been disclosed to the public and may be used. VDB-251382 is the identifier assigned to this vulnerability."
                },
                {
                    "lang": "de",
                    "value": "Es wurde eine Schwachstelle in DeepFaceLab pretrained DF.wf.288res.384.92.72.22 gefunden. Sie wurde als problematisch eingestuft. Es geht dabei um eine nicht klar definierte Funktion der Datei mainscripts/Util.py. Durch Beeinflussen mit unbekannten Daten kann eine deserialization-Schwachstelle ausgenutzt werden. Der Angriff hat dabei lokal zu erfolgen. Der Exploit steht zur öffentlichen Verfügung."
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "version": "3.1",
                        "baseScore": 5.3,
                        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
                        "baseSeverity": "MEDIUM"
                    }
                },
                {
                    "cvssV3_0": {
                        "version": "3.0",
                        "baseScore": 5.3,
                        "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
                        "baseSeverity": "MEDIUM"
                    }
                },
                {
                    "cvssV2_0": {
                        "version": "2.0",
                        "baseScore": 4.3,
                        "vectorString": "AV:L/AC:L/Au:S/C:P/I:P/A:P"
                    }
                }
            ],
            "timeline": [
                {
                    "time": "2024-01-17T00:00:00.000Z",
                    "lang": "en",
                    "value": "Advisory disclosed"
                },
                {
                    "time": "2024-01-17T00:00:00.000Z",
                    "lang": "en",
                    "value": "CVE reserved"
                },
                {
                    "time": "2024-01-17T01:00:00.000Z",
                    "lang": "en",
                    "value": "VulDB entry created"
                },
                {
                    "time": "2024-02-10T19:43:51.000Z",
                    "lang": "en",
                    "value": "VulDB entry last update"
                }
            ],
            "credits": [
                {
                    "lang": "en",
                    "value": "bayuncao (VulDB User)",
                    "type": "reporter"
                }
            ],
            "references": [
                {
                    "url": "https://vuldb.com/?id.251382",
                    "tags": [
                        "vdb-entry",
                        "technical-description"
                    ]
                },
                {
                    "url": "https://vuldb.com/?ctiid.251382",
                    "tags": [
                        "signature",
                        "permissions-required"
                    ]
                },
                {
                    "url": "https://github.com/bayuncao/vul-cve-4",
                    "tags": [
                        "broken-link"
                    ]
                },
                {
                    "url": "https://github.com/bayuncao/vul-cve-4/blob/main/picture/1071705290840_.pic_hd.jpg",
                    "tags": [
                        "broken-link",
                        "exploit"
                    ]
                }
            ]
        }
    }
}