{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "cveMetadata": {
        "cveId": "CVE-2023-31125",
        "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "state": "PUBLISHED",
        "assignerShortName": "GitHub_M",
        "dateReserved": "2023-04-24T21:44:10.415Z",
        "datePublished": "2023-05-08T20:21:01.341Z",
        "dateUpdated": "2023-05-08T20:21:01.341Z"
    },
    "containers": {
        "cna": {
            "title": "Uncaught exception in engine.io ",
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-248",
                            "lang": "en",
                            "description": "CWE-248: Uncaught Exception",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 6.5,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                        "version": "3.1"
                    }
                }
            ],
            "references": [
                {
                    "name": "https://github.com/socketio/engine.io/security/advisories/GHSA-q9mw-68c2-j6m5",
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://github.com/socketio/engine.io/security/advisories/GHSA-q9mw-68c2-j6m5"
                },
                {
                    "name": "https://github.com/socketio/engine.io/commit/fc480b4f305e16fe5972cf337d055e598372dc44",
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/socketio/engine.io/commit/fc480b4f305e16fe5972cf337d055e598372dc44"
                },
                {
                    "name": "https://github.com/socketio/engine.io/releases/tag/6.4.2",
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/socketio/engine.io/releases/tag/6.4.2"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20230622-0002/"
                }
            ],
            "affected": [
                {
                    "vendor": "socketio",
                    "product": "engine.io",
                    "versions": [
                        {
                            "version": ">= 5.1.0, < 6.4.2",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
                "shortName": "GitHub_M",
                "dateUpdated": "2023-05-08T20:21:01.341Z"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Engine.IO is the implementation of transport-based cross-browser/cross-device bi-directional communication layer for Socket.IO. An uncaught exception vulnerability was introduced in version 5.1.0 and included in version 4.1.0 of the `socket.io` parent package. Older versions are not impacted. A specially crafted HTTP request can trigger an uncaught exception on the Engine.IO server, thus killing the Node.js process. This impacts all the users of the `engine.io` package, including those who use depending packages like `socket.io`. This issue was fixed in version 6.4.2 of Engine.IO. There is no known workaround except upgrading to a safe version.\n"
                }
            ],
            "source": {
                "advisory": "GHSA-q9mw-68c2-j6m5",
                "discovery": "UNKNOWN"
            }
        }
    }
}