{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "cveMetadata": {
        "cveId": "CVE-2023-40170",
        "assignerOrgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
        "state": "PUBLISHED",
        "assignerShortName": "GitHub_M",
        "dateReserved": "2023-08-09T15:26:41.051Z",
        "datePublished": "2023-08-28T20:01:57.156Z",
        "dateUpdated": "2023-08-28T20:01:57.156Z"
    },
    "containers": {
        "cna": {
            "title": "cross-site inclusion (XSSI) of files in jupyter-server",
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-284",
                            "lang": "en",
                            "description": "CWE-284: Improper Access Control",
                            "type": "CWE"
                        }
                    ]
                },
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-306",
                            "lang": "en",
                            "description": "CWE-306: Missing Authentication for Critical Function",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "attackComplexity": "LOW",
                        "attackVector": "NETWORK",
                        "availabilityImpact": "NONE",
                        "baseScore": 4.6,
                        "baseSeverity": "MEDIUM",
                        "confidentialityImpact": "LOW",
                        "integrityImpact": "LOW",
                        "privilegesRequired": "LOW",
                        "scope": "UNCHANGED",
                        "userInteraction": "REQUIRED",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:N",
                        "version": "3.1"
                    }
                }
            ],
            "references": [
                {
                    "name": "https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-64x5-55rw-9974",
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://github.com/jupyter-server/jupyter_server/security/advisories/GHSA-64x5-55rw-9974"
                },
                {
                    "name": "https://github.com/jupyter-server/jupyter_server/commit/87a4927272819f0b1cae1afa4c8c86ee2da002fd",
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/jupyter-server/jupyter_server/commit/87a4927272819f0b1cae1afa4c8c86ee2da002fd"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XDKQAWQN6SQTOVACZNXYKEHWQXGG4DOF/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NRP7DNZYVOIA4ZB3U3ZWKTFZEPYWNGCQ/"
                }
            ],
            "affected": [
                {
                    "vendor": "jupyter-server",
                    "product": "jupyter_server",
                    "versions": [
                        {
                            "version": "< 2.7.2",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "a0819718-46f1-4df5-94e2-005712e83aaa",
                "shortName": "GitHub_M",
                "dateUpdated": "2023-08-28T20:01:57.156Z"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "jupyter-server is the backend for Jupyter web applications. Improper cross-site credential checks on `/files/` URLs could allow exposure of certain file contents, or accessing files when opening untrusted files via  \"Open image in new tab\". This issue has been addressed in commit `87a49272728` which has been included in release `2.7.2`. Users are advised to upgrade. Users unable to upgrade may use the lower performance `--ContentsManager.files_handler_class=jupyter_server.files.handlers.FilesHandler`, which implements the correct checks."
                }
            ],
            "source": {
                "advisory": "GHSA-64x5-55rw-9974",
                "discovery": "UNKNOWN"
            }
        }
    }
}